- hosts: master
  vars_files:
   - vars/var_java.yml
   - vars/var_worker.yml
   - vars/var_hadoop.yml
   - vars/var_master.yml
  vars:
    add_user: true           # add user "hadoop"
    generate_key: true       # generate the ssh key
    open_firewall: true      # configure firewalld for hadooop
    disable_firewall: false  # disable firewalld
    install_hadoop: true     # install hadoop,if you just want to update the configuration, set to false
    config_hadoop: true      # Update configuration
  roles:
    - user                              # add user and generate the ssh key
    - fetch_public_key_of_master        # get the key and put it in your localhost
    - authorized                        # push the ssh key to the remote server 
    - common                            # install common packages
    - java                              # install jdk 
    - hadoop                            # install hadoop