---

- name: create ssh user
  shell: lxc-attach -n {{ current_host }} -- useradd -m -d {{ worker_home }} -s /bin/bash {{ worker_user }} 
  when: "worker_user not in worker_is_pressend.stdout"

- name: set password
  shell: "lxc-attach -n {{ current_host }} -- echo {{ worker_pass }}:{{ worker_user }} | chpasswd"
  when: "worker_user not in worker_is_pressend.stdout"

- name: add user to group wheel for privilege escalation
  shell: "lxc-attach -n {{ current_host }} -- usermod -aG sudo {{ worker_user }}"
  when: "worker_user not in worker_is_pressend.stdout"

...