---

- hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:

  - name: install python
    package:
      name: python2
      state: present
   
  - name: add ssh key for root user
    authorized_key: user=root
                    exclusive=no
                    key="{{ lookup('file', '~/Projects/ansible/host/demo_key.pub') }}"

  - name: COMMON | Set environment
    blockinfile:
      dest: /etc/environment
      block: |
        LC_ALL=de_DE.UTF-8
        LANG=de_DE.UTF-8
    register: newenv
    
  - block:
    - name: COMMON | Generate locales
      raw: locale-gen de_DE.UTF-8

    - name: COMMON | Reconfigure locales
      raw: dpkg-reconfigure locales
      # only run this task block when we've just changed /etc/environment
      when: newenv.changed