---
- name: COMMON | Install basic packages
  package: name={{ item }} state=present
  with_items:
    - wget
    - nano
    - curl
    - tar
    - firewalld
    - python3-firewall

- include_tasks: create_folders.yml

- include_tasks: start-services.yml