---
- name: Enable Firewalld
  systemd:
    state: started
    name: firewalld
  when: not disable_firewall

- name: Disabled Firewalld
  systemd:
    name: 'firewalld'
    state: stopped
    enabled: no
  when: disable_firewall
  ignore_errors: true
